app:
  baseUrl: http://localhost:7007

backend:
  baseUrl: http://localhost:7007
  listen: ':7007'

  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}

auth:
  environment: production
  providers:
    guest: {}
    ldap:
      production:
        cookies:
          secure: false
          field: 'backstage-token'
        ldapAuthenticationOptions:
          userSearchBase: 'OU=NPCI Users,OU=NPCI,DC=npci,DC=org,DC=in'
          usernameAttribute: 'mail'
          adminDn: 'CN=Hadoop Admin,OU=Server Service Account,OU=Servers,DC=npci,DC=org,DC=in'
          adminPassword: '${LDAP_ADMIN_PASSWORD}'
          ldapOpts:
            url: '<the url your IT dude gave>'

catalog:
  locations:
    - type: file
      target: ./examples/entities.yaml

    - type: file
      target: ./examples/template/template.yaml
      rules:
        - allow: [Template]

    - type: file
      target: ./examples/org.yaml
      rules:
        - allow: [User, Group]