app:
  title: Scaffolded Backstage App
  baseUrl: http://localhost:3000

  packages: all

  extensions:
    - page:catalog:
        config:
          path: /
    - catalog-filter:catalog/list:
        config:
          initialFilter: all

organization:
  name: NPCI

backend:
  baseUrl: http://localhost:7007
  listen:
    port: 7007
  csp:
    connect-src: ["'self'", 'http:', 'https:']
  cors:
    origin: http://localhost:3000
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  database:
    client: better-sqlite3
    connection: ':memory:'

integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}
  gitlab:
    - host: gitlab.com
      token: glpat-ENgmfpdJiV6Q2i0Htuq4F2M6MQpvOjEKdTpuMGd1Ng8.01.170k11kwi

proxy:

techdocs:
  builder: 'local'
  generator:
    runIn: 'docker'
  publisher:
    type: 'local'

auth:
  environment: development
  providers:
    ldap:
      development:
        cookies:
          secure: false
          field: 'backstage-token'
        ldapAuthenticationOptions:
          userSearchBase: 'OU=NPCI Users,OU=NPCI,DC=npci,DC=org,DC=in'
          usernameAttribute: 'sAMAccountName'
          adminDn: 'CN=Hadoop Admin,OU=Server Service Account,OU=Servers,DC=npci,DC=org,DC=in'
          adminPassword: 'Securegen@229933$'
          ldapOpts:
            url: 'ldaps://10.88.1.121:636'
    guest: {}

scaffolder:

catalog:
  providers:
    ldapOrg:
      default:
        target: ldaps://10.88.1.121:636
        bind:
          dn: 'CN=Hadoop Admin,OU=Server Service Account,OU=Servers,DC=npci,DC=org,DC=in'
          secret: 'Securegen@229933$'
        users:
          - dn: 'OU=NPCI Users,OU=NPCI,DC=npci,DC=org,DC=in'
            options:
              filter: (&(objectClass=user)(!(objectClass=computer)))
            map:
              rdn: cn
              name: sAMAccountName
              displayName: displayName
              email: mail
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, System, API, Resource, Location]
  locations:
    # Groups (and only Groups) come from a local file for now;
    # later swap to the GitLab-hosted URL when ready.
    - type: file
      target: ../../examples/groups.yaml
      rules:
        - allow: [Group]

    - type: file
      target: ../../examples/entities.yaml

    - type: file
      target: ../../examples/template/template.yaml
      rules:
        - allow: [Template]

    - type: file
      target: ../../examples/test-service.yaml

    - type: file
      target: ../../examples/market-innovation.yaml
      rules:
        - allow: [System]

    - type: file
      target: ../../examples/test-service-api.yaml
      rules:
        - allow: [API]

    - type: file
      target: ../../examples/test-db.yaml
      rules:
        - allow: [Resource]

    - type: file
      target: ../../examples/chat-api.yaml
      rules:
        - allow: [API]

kubernetes:

permission:
  enabled: true

productionRequests:
  jenkins:
    baseUrl: http://localhost:8080
    username: aryan_saket
    apiToken: 11b2713664d7358543e408c1e75ab4a81c
  gitlab:
    apiToken: glpat-ENgmfpdJiV6Q2i0Htuq4F2M6MQpvOjEKdTpuMGd1Ng8.01.170k11kwi
    issueProject: 'saket.aryanr64x-group/manifests'
  argocd:
    baseUrl: http://localhost:8081
    apiToken: replace-me-with-argocd-api-token